services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - my-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
